#!/usr/bin/env python3
"""Generate the checked-in C++ FlexiCubes lookup tables from the official source.

The native mesh extractor intentionally consumes the same DMC tables as
``sam3d_objects/.../flexicubes/tables.py``.  This tool uses ``ast`` rather
than importing Torch so generation and CI validation do not acquire a Python
runtime dependency for the C++ application.
"""

import argparse
import ast
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SOURCE = ROOT / "sam3d_objects/model/backbone/tdfy_dit/representations/mesh/flexicubes/tables.py"
DEFAULT_OUTPUT = ROOT / "cpp_ggml/src/flexicubes_tables.hpp"
TABLE_NAMES = ("dmc_table", "num_vd_table", "check_table")


def load_tables(path: Path) -> dict[str, object]:
    parsed = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    values: dict[str, object] = {}
    for node in parsed.body:
        if not isinstance(node, ast.Assign):
            continue
        for target in node.targets:
            if isinstance(target, ast.Name) and target.id in TABLE_NAMES:
                values[target.id] = ast.literal_eval(node.value)
    missing = [name for name in TABLE_NAMES if name not in values]
    if missing:
        raise ValueError(f"{path}: missing table(s): {', '.join(missing)}")
    if len(values["dmc_table"]) != 256 or any(
        len(case) != 4 or any(len(edges) != 7 for edges in case)
        for case in values["dmc_table"]
    ):
        raise ValueError("dmc_table must be [256][4][7]")
    if len(values["num_vd_table"]) != 256:
        raise ValueError("num_vd_table must have 256 entries")
    if len(values["check_table"]) != 256 or any(len(row) != 5 for row in values["check_table"]):
        raise ValueError("check_table must be [256][5]")
    return values


def render_array(value: object, indent: int = 0) -> str:
    prefix = " " * indent
    if not isinstance(value, list):
        return str(value)
    if not value:
        return "{}"
    if not isinstance(value[0], list):
        return "{" + ", ".join(str(item) for item in value) + "}"
    lines = ["{"]
    for item in value:
        lines.append(prefix + "    " + render_array(item, indent + 4) + ",")
    lines.append(prefix + "}")
    return "\n".join(lines)


def render(tables: dict[str, object]) -> str:
    return """// Generated by scripts/generate_flexicubes_tables.py. DO NOT EDIT.\n//\n// Source: sam3d_objects/model/backbone/tdfy_dit/representations/mesh/\n// flexicubes/tables.py (Copyright (c) Meta Platforms, Inc. and affiliates).\n// The generator is part of the source contract and is checked in CTest.\n#pragma once\n\n#include <cstdint>\n\nnamespace sam3d::flexicubes_tables {\n\ninline constexpr int8_t kDmcTable[256][4][7] = """ + render_array(tables["dmc_table"]) + ";\n\ninline constexpr int8_t kNumVdTable[256] = " + render_array(tables["num_vd_table"]) + ";\n\ninline constexpr int16_t kCheckTable[256][5] = " + render_array(tables["check_table"]) + ";\n\n}  // namespace sam3d::flexicubes_tables\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail when --out is stale")
    args = parser.parse_args()
    expected = render(load_tables(args.source))
    if args.check:
        if not args.out.is_file() or args.out.read_text(encoding="utf-8") != expected:
            raise SystemExit(f"stale generated FlexiCubes table: {args.out}; rerun {Path(__file__).name}")
        print(f"FlexiCubes table check: PASS ({args.out})")
        return
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(expected, encoding="utf-8")
    print(f"generated {args.out}")


if __name__ == "__main__":
    main()
