#!/usr/bin/env python3
"""Generate the fixed official 1000-view _fill_holes camera contract.

The official pipeline constructs this trajectory through mixed F32/F64 PyTorch
operations.  The generated header is a build-time source artifact: C++ never
imports Python or PyTorch at runtime.  Keep the generated table only for the
official 1000-view contract; other view counts use the native formula.
"""
from __future__ import annotations

import argparse
import importlib.util
from pathlib import Path

import numpy as np


def load_official_visibility_matrices(view_count: int) -> tuple[np.ndarray, np.ndarray]:
    script = Path(__file__).with_name("verify_mesh_camera_contract.py")
    spec = importlib.util.spec_from_file_location("sam3d_mesh_camera_contract", script)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {script}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.official_visibility_matrices(view_count)


def cpp_float(value: np.float32) -> str:
    return f"{float(value).hex()}f"


def emit_array(lines: list[str], name: str, values: np.ndarray) -> None:
    lines.append(f"inline constexpr std::array<float, {values.size}> {name} = {{")
    flattened = values.reshape(-1)
    for begin in range(0, flattened.size, 8):
        lines.append("    " + ", ".join(cpp_float(value) for value in flattened[begin : begin + 8]) + ",")
    lines.append("};")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--views", type=int, default=1000)
    args = parser.parse_args()
    if args.views != 1000:
        raise ValueError("the committed native contract is the official 1000-view trajectory")
    views, projections = load_official_visibility_matrices(args.views)
    if views.shape != (args.views, 4, 4) or projections.shape != views.shape:
        raise ValueError(f"unexpected official camera shapes: {views.shape}, {projections.shape}")
    # CUDA/cuBLAS consumes column-major matrices.  Serialize in that layout to
    # avoid a runtime transpose and preserve the exact source float bits.
    views_column_major = np.ascontiguousarray(np.transpose(views, (0, 2, 1)))
    projection_column_major = np.ascontiguousarray(projections[0].T)
    lines = [
        "// Generated by scripts/generate_mesh_visibility_camera_reference.py.",
        "// Do not edit by hand; regenerate with the pinned official PyTorch environment.",
        "#pragma once",
        "",
        "#include <array>",
        "",
        "namespace sam3d::detail {",
        f"inline constexpr int kOfficialVisibilityViewCount = {args.views};",
    ]
    emit_array(lines, "kOfficialVisibilityViewsColumnMajor", views_column_major)
    emit_array(lines, "kOfficialVisibilityProjectionColumnMajor", projection_column_major)
    lines.append("}  // namespace sam3d::detail")
    lines.append("")
    args.out.write_text("\n".join(lines), encoding="ascii")
    print(f"wrote {args.out} ({views_column_major.size} view values)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
