#!/usr/bin/env python3
"""Generate the official CUDA APE lookup used by the native mesh decoder.

``AbsolutePositionEmbedder`` evaluates its F32 frequencies on the host and
then calls ``torch.outer``, ``torch.sin`` and ``torch.cos`` on CUDA.  The
released mesh decoder has integer base-grid positions in ``[0, 63]``.  This
tool freezes that finite official contract as IEEE-754 words so the native
runtime does not depend on Python, PyTorch or host libm at inference time.

Run it only from the pinned official PyTorch environment when upgrading the
reference model or its PyTorch/CUDA contract.  It writes a source header and
never changes a runtime model or a benchmark artifact.
"""
from __future__ import annotations

import argparse
import os
import struct
import sys
from pathlib import Path

os.environ.setdefault("LIDRA_SKIP_INIT", "true")

import torch


REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))


def float_bits(value: float) -> int:
    return struct.unpack("<I", struct.pack("<f", value))[0]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=REPO_ROOT / "src" / "mesh_ape_reference.hpp",
    )
    args = parser.parse_args()
    if not torch.cuda.is_available():
        raise RuntimeError("the official APE contract must be generated on CUDA")

    from sam3d_objects.model.backbone.tdfy_dit.modules.transformer import (  # noqa: PLC0415
        AbsolutePositionEmbedder,
    )

    coordinate_count = 64
    frequency_count = 128
    embedder = AbsolutePositionEmbedder(channels=768).cuda().eval()
    coordinates = torch.arange(coordinate_count, dtype=torch.float32, device="cuda")
    with torch.inference_mode():
        # Calling the released module method preserves its exact frequency
        # transfer, outer product and CUDA trigonometric dispatch.
        embedding = embedder._sin_cos_embedding(coordinates).cpu().contiguous()
    if embedding.shape != (coordinate_count, frequency_count * 2):
        raise RuntimeError(f"unexpected APE shape: {tuple(embedding.shape)}")

    values = embedding.numpy()
    lines = [
        "// Generated by scripts/generate_mesh_ape_reference.py. DO NOT EDIT.",
        "// Official AbsolutePositionEmbedder CUDA F32 values for coordinates 0..63.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace sam3d::mesh_ape_reference {",
        f"constexpr int kCoordinateCount = {coordinate_count};",
        f"constexpr int kFrequencyCount = {frequency_count};",
        "constexpr uint32_t kSinCosBits[kCoordinateCount][2][kFrequencyCount] = {",
    ]
    for coordinate in range(coordinate_count):
        lines.append("    {")
        for trig_index, name in enumerate(("sin", "cos")):
            start = trig_index * frequency_count
            words = [float_bits(float(value)) for value in values[coordinate, start:start + frequency_count]]
            lines.append(f"        {{  // {name}")
            for offset in range(0, frequency_count, 8):
                part = ", ".join(f"0x{word:08x}u" for word in words[offset:offset + 8])
                lines.append(f"            {part},")
            lines.append("        },")
        lines.append("    },")
    lines.extend(("};", "}  // namespace sam3d::mesh_ape_reference", ""))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding="ascii")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
